/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.1.0 Sun Jun 26 23:31:05 2022.
 */

#include <string.h>

#include "bps.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int bps_bps_pack_information_pack(
    uint8_t *dst_p,
    const struct bps_bps_pack_information_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->pack_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pack_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pack_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pack_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->pack_soc, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->discharge_relay_status, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->charge_relay_status, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->charger_safety_status, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->dtc_status, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->multipurpose_input_signal_status, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->always_on_signal_status, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->is_ready_signal_status, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->is_charging_signal_status, 7u, 0x80u);

    return (6);
}

int bps_bps_pack_information_unpack(
    struct bps_bps_pack_information_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->pack_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pack_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pack_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pack_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->pack_soc = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->discharge_relay_status = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->charge_relay_status = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->charger_safety_status = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->dtc_status = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->multipurpose_input_signal_status = unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    dst_p->always_on_signal_status = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->is_ready_signal_status = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->is_charging_signal_status = unpack_right_shift_u8(src_p[5], 7u, 0x80u);

    return (0);
}

uint16_t bps_bps_pack_information_pack_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double bps_bps_pack_information_pack_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool bps_bps_pack_information_pack_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bps_bps_pack_information_pack_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double bps_bps_pack_information_pack_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool bps_bps_pack_information_pack_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_bps_pack_information_pack_soc_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double bps_bps_pack_information_pack_soc_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool bps_bps_pack_information_pack_soc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_bps_pack_information_discharge_relay_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_discharge_relay_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_discharge_relay_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_pack_information_charge_relay_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_charge_relay_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_charge_relay_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_pack_information_charger_safety_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_charger_safety_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_charger_safety_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_pack_information_dtc_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_dtc_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_dtc_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_pack_information_multipurpose_input_signal_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_multipurpose_input_signal_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_multipurpose_input_signal_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_pack_information_always_on_signal_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_always_on_signal_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_always_on_signal_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_pack_information_is_ready_signal_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_is_ready_signal_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_is_ready_signal_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_pack_information_is_charging_signal_status_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_pack_information_is_charging_signal_status_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_pack_information_is_charging_signal_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int bps_bps_cell_voltage_pack(
    uint8_t *dst_p,
    const struct bps_bps_cell_voltage_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->low_cell_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->low_cell_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->low_cell_voltage_id, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->high_cell_voltage, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->high_cell_voltage, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->high_cell_voltage_id, 0u, 0xffu);

    return (6);
}

int bps_bps_cell_voltage_unpack(
    struct bps_bps_cell_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->low_cell_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->low_cell_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->low_cell_voltage_id = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->high_cell_voltage = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->high_cell_voltage |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->high_cell_voltage_id = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

uint16_t bps_bps_cell_voltage_low_cell_voltage_encode(double value)
{
    return (uint16_t)(value / 0.0001);
}

double bps_bps_cell_voltage_low_cell_voltage_decode(uint16_t value)
{
    return ((double)value * 0.0001);
}

bool bps_bps_cell_voltage_low_cell_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_bps_cell_voltage_low_cell_voltage_id_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_cell_voltage_low_cell_voltage_id_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_cell_voltage_low_cell_voltage_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t bps_bps_cell_voltage_high_cell_voltage_encode(double value)
{
    return (uint16_t)(value / 0.0001);
}

double bps_bps_cell_voltage_high_cell_voltage_decode(uint16_t value)
{
    return ((double)value * 0.0001);
}

bool bps_bps_cell_voltage_high_cell_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_bps_cell_voltage_high_cell_voltage_id_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_cell_voltage_high_cell_voltage_id_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_cell_voltage_high_cell_voltage_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int bps_bps_cell_temperature_pack(
    uint8_t *dst_p,
    const struct bps_bps_cell_temperature_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->low_temperature, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->low_thermistor_id, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->high_temperature, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->high_thermistor_id, 0u, 0xffu);

    return (4);
}

int bps_bps_cell_temperature_unpack(
    struct bps_bps_cell_temperature_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->low_temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->low_thermistor_id = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->high_temperature = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->high_thermistor_id = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

uint8_t bps_bps_cell_temperature_low_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_cell_temperature_low_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_cell_temperature_low_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_bps_cell_temperature_low_thermistor_id_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_cell_temperature_low_thermistor_id_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_cell_temperature_low_thermistor_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_bps_cell_temperature_high_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_cell_temperature_high_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_cell_temperature_high_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bps_bps_cell_temperature_high_thermistor_id_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_cell_temperature_high_thermistor_id_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_cell_temperature_high_thermistor_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int bps_bps_error_pack(
    uint8_t *dst_p,
    const struct bps_bps_error_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->internal_communications_fault, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->internal_conversion_fault, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->weak_cell_fault, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->low_cell_voltage_fault, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->open_wiring_fault, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->current_sensor_fault, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->pack_voltage_sensor_fault, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->weak_pack_fault, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->voltage_redundancy_fault, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->fan_monitor_fault, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->thermistor_fault, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->canbus_communications_fault, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->always_on_supply_fault, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->high_voltage_isolation_fault, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->power_supply_12v_fault, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->charge_limit_enforcement_fault, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->discharge_limit_enforcement_fault, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->charger_safety_relay_fault, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->internal_memory_fault, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->internal_thermistor_fault, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->internal_logic_fault, 4u, 0x10u);

    return (3);
}

int bps_bps_error_unpack(
    struct bps_bps_error_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->internal_communications_fault = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->internal_conversion_fault = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->weak_cell_fault = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->low_cell_voltage_fault = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->open_wiring_fault = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->current_sensor_fault = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->pack_voltage_sensor_fault = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->weak_pack_fault = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->voltage_redundancy_fault = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->fan_monitor_fault = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->thermistor_fault = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->canbus_communications_fault = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->always_on_supply_fault = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->high_voltage_isolation_fault = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->power_supply_12v_fault = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->charge_limit_enforcement_fault = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->discharge_limit_enforcement_fault = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->charger_safety_relay_fault = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->internal_memory_fault = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->internal_thermistor_fault = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->internal_logic_fault = unpack_right_shift_u8(src_p[2], 4u, 0x10u);

    return (0);
}

uint8_t bps_bps_error_internal_communications_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_internal_communications_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_internal_communications_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_internal_conversion_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_internal_conversion_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_internal_conversion_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_weak_cell_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_weak_cell_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_weak_cell_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_low_cell_voltage_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_low_cell_voltage_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_low_cell_voltage_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_open_wiring_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_open_wiring_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_open_wiring_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_current_sensor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_current_sensor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_current_sensor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_pack_voltage_sensor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_pack_voltage_sensor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_pack_voltage_sensor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_weak_pack_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_weak_pack_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_weak_pack_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_voltage_redundancy_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_voltage_redundancy_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_voltage_redundancy_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_fan_monitor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_fan_monitor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_fan_monitor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_thermistor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_thermistor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_thermistor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_canbus_communications_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_canbus_communications_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_canbus_communications_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_always_on_supply_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_always_on_supply_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_always_on_supply_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_high_voltage_isolation_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_high_voltage_isolation_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_high_voltage_isolation_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_power_supply_12v_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_power_supply_12v_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_power_supply_12v_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_charge_limit_enforcement_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_charge_limit_enforcement_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_charge_limit_enforcement_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_discharge_limit_enforcement_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_discharge_limit_enforcement_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_discharge_limit_enforcement_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_charger_safety_relay_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_charger_safety_relay_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_charger_safety_relay_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_internal_memory_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_internal_memory_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_internal_memory_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_internal_thermistor_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_internal_thermistor_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_internal_thermistor_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bps_bps_error_internal_logic_fault_encode(double value)
{
    return (uint8_t)(value);
}

double bps_bps_error_internal_logic_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool bps_bps_error_internal_logic_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
