// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "ecu_bp.h"

void BpFieldDescriptorsInitBitprotoECUMotorCommands(struct BitprotoECUMotorCommands *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->throttle), BpUint(8, sizeof(uint8_t)), "throttle");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->regen), BpUint(8, sizeof(uint8_t)), "regen");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->forward_en), BpBool(), "forward_en");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->reverse_en), BpBool(), "reverse_en");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->cruise_control_en), BpBool(), "cruise_control_en");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->cruise_control_speed), BpUint(8, sizeof(uint8_t)), "cruise_control_speed");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->motor_on), BpBool(), "motor_on");
}

void BpXXXProcessBitprotoECUMotorCommands(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoECUMotorCommands *m = (struct BitprotoECUMotorCommands *)(data);
    struct BpMessageFieldDescriptor field_descriptors[7];
    BpFieldDescriptorsInitBitprotoECUMotorCommands(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 7, 28, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoECUMotorCommands(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoECUMotorCommands *m = (struct BitprotoECUMotorCommands *)(data);
    struct BpMessageFieldDescriptor field_descriptors[7];
    BpFieldDescriptorsInitBitprotoECUMotorCommands(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 7, 28, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoECUMotorCommands(struct BitprotoECUMotorCommands *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoECUMotorCommands((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoECUMotorCommands(struct BitprotoECUMotorCommands *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoECUMotorCommands((void *)m, &ctx);
    return 0;
}

int JsonBitprotoECUMotorCommands(struct BitprotoECUMotorCommands *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoECUMotorCommands((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBitprotoECUPowerAuxCommands(struct BitprotoECUPowerAuxCommands *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->hazards), BpBool(), "hazards");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->brake_lights), BpBool(), "brake_lights");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->headlights), BpBool(), "headlights");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->left_turn_signal), BpBool(), "left_turn_signal");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->right_turn_signal), BpBool(), "right_turn_signal");
}

void BpXXXProcessBitprotoECUPowerAuxCommands(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoECUPowerAuxCommands *m = (struct BitprotoECUPowerAuxCommands *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitBitprotoECUPowerAuxCommands(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 5, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoECUPowerAuxCommands(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoECUPowerAuxCommands *m = (struct BitprotoECUPowerAuxCommands *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitBitprotoECUPowerAuxCommands(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 5, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoECUPowerAuxCommands(struct BitprotoECUPowerAuxCommands *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoECUPowerAuxCommands((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoECUPowerAuxCommands(struct BitprotoECUPowerAuxCommands *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoECUPowerAuxCommands((void *)m, &ctx);
    return 0;
}

int JsonBitprotoECUPowerAuxCommands(struct BitprotoECUPowerAuxCommands *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoECUPowerAuxCommands((void *)m, &ctx);
    return ctx.n;
}