// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__ID_H__
#define __BITPROTO__ID_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Errors -------------------------------------------
#define BPSError_MESSAGE_ID 262

#define MotorControllerError_MESSAGE_ID 277

#define PowerAuxError_MESSAGE_ID 291

// Critical functions -------------------------------
#define ECUMotorCommands_MESSAGE_ID 513

// Non-critical functions ---------------------------
#define ECUPowerAuxCommands_MESSAGE_ID 769

#define MotorControllerDriveStatus_MESSAGE_ID 789

#define MotorControllerPowerStatus_MESSAGE_ID 805

// Diagnostic information ---------------------------
#define BPSPackInformation_MESSAGE_ID 1030

#define BPSCellVoltage_MESSAGE_ID 1046

#define BPSCellTemperature_MESSAGE_ID 1062

#define SolarCurrent_MESSAGE_ID 1076

#define SolarVoltage_MESSAGE_ID 1092

#define SolarTemp_MESSAGE_ID 1108

#define SolarPhoto_MESSAGE_ID 1124

#if defined(__cplusplus)
}
#endif

#endif