// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "motor_controller_bp.h"

void BpFieldDescriptorsInitBitprotoMotorControllerFrameRequest(struct BitprotoMotorControllerFrameRequest *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->power_status_frame), BpBool(), "power_status_frame");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->drive_status_frame), BpBool(), "drive_status_frame");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->errors_frame), BpBool(), "errors_frame");
}

void BpXXXProcessBitprotoMotorControllerFrameRequest(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoMotorControllerFrameRequest *m = (struct BitprotoMotorControllerFrameRequest *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitBitprotoMotorControllerFrameRequest(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 3, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoMotorControllerFrameRequest(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoMotorControllerFrameRequest *m = (struct BitprotoMotorControllerFrameRequest *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitBitprotoMotorControllerFrameRequest(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 3, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoMotorControllerFrameRequest(struct BitprotoMotorControllerFrameRequest *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoMotorControllerFrameRequest((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoMotorControllerFrameRequest(struct BitprotoMotorControllerFrameRequest *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoMotorControllerFrameRequest((void *)m, &ctx);
    return 0;
}

int JsonBitprotoMotorControllerFrameRequest(struct BitprotoMotorControllerFrameRequest *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoMotorControllerFrameRequest((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBitprotoMotorControllerPowerStatus(struct BitprotoMotorControllerPowerStatus *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->battery_voltage), BpUint(10, sizeof(uint16_t)), "battery_voltage");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->battery_current), BpUint(9, sizeof(uint16_t)), "battery_current");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->battery_current_direction), BpBool(), "battery_current_direction");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->motor_current), BpUint(10, sizeof(uint16_t)), "motor_current");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->fet_temperature), BpUint(5, sizeof(uint8_t)), "fet_temperature");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->motor_rotating_speed), BpUint(12, sizeof(uint16_t)), "motor_rotating_speed");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->pwm_duty), BpUint(10, sizeof(uint16_t)), "pwm_duty");
    fds[7] = BpMessageFieldDescriptor((void *)&(m->advanced_lead_angle), BpUint(7, sizeof(uint8_t)), "advanced_lead_angle");
}

void BpXXXProcessBitprotoMotorControllerPowerStatus(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoMotorControllerPowerStatus *m = (struct BitprotoMotorControllerPowerStatus *)(data);
    struct BpMessageFieldDescriptor field_descriptors[8];
    BpFieldDescriptorsInitBitprotoMotorControllerPowerStatus(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 8, 64, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoMotorControllerPowerStatus(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoMotorControllerPowerStatus *m = (struct BitprotoMotorControllerPowerStatus *)(data);
    struct BpMessageFieldDescriptor field_descriptors[8];
    BpFieldDescriptorsInitBitprotoMotorControllerPowerStatus(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 8, 64, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoMotorControllerPowerStatus(struct BitprotoMotorControllerPowerStatus *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoMotorControllerPowerStatus((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoMotorControllerPowerStatus(struct BitprotoMotorControllerPowerStatus *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoMotorControllerPowerStatus((void *)m, &ctx);
    return 0;
}

int JsonBitprotoMotorControllerPowerStatus(struct BitprotoMotorControllerPowerStatus *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoMotorControllerPowerStatus((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBitprotoMotorControllerDriveStatus(struct BitprotoMotorControllerDriveStatus *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->power_eco), BpBool(), "power_eco");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->control_mode), BpBool(), "control_mode");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->acceleration_vr_position), BpUint(10, sizeof(uint16_t)), "acceleration_vr_position");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->regeneration_vr_position), BpUint(10, sizeof(uint16_t)), "regeneration_vr_position");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->digi_sw_number), BpUint(4, sizeof(uint8_t)), "digi_sw_number");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->target_value), BpUint(10, sizeof(uint16_t)), "target_value");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->motor_status), BpUint(2, sizeof(uint8_t)), "motor_status");
    fds[7] = BpMessageFieldDescriptor((void *)&(m->drive_regen), BpBool(), "drive_regen");
}

void BpXXXProcessBitprotoMotorControllerDriveStatus(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoMotorControllerDriveStatus *m = (struct BitprotoMotorControllerDriveStatus *)(data);
    struct BpMessageFieldDescriptor field_descriptors[8];
    BpFieldDescriptorsInitBitprotoMotorControllerDriveStatus(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 8, 39, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoMotorControllerDriveStatus(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoMotorControllerDriveStatus *m = (struct BitprotoMotorControllerDriveStatus *)(data);
    struct BpMessageFieldDescriptor field_descriptors[8];
    BpFieldDescriptorsInitBitprotoMotorControllerDriveStatus(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 8, 39, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoMotorControllerDriveStatus(struct BitprotoMotorControllerDriveStatus *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoMotorControllerDriveStatus((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoMotorControllerDriveStatus(struct BitprotoMotorControllerDriveStatus *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoMotorControllerDriveStatus((void *)m, &ctx);
    return 0;
}

int JsonBitprotoMotorControllerDriveStatus(struct BitprotoMotorControllerDriveStatus *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoMotorControllerDriveStatus((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBitprotoMotorControllerError(struct BitprotoMotorControllerError *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->analog_sensor_error), BpBool(), "analog_sensor_error");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->motor_current_sensor_u_error), BpBool(), "motor_current_sensor_u_error");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->motor_current_sensor_w_error), BpBool(), "motor_current_sensor_w_error");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->fet_thermistor_error), BpBool(), "fet_thermistor_error");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->padding0), BpUint(1, sizeof(uint8_t)), "padding0");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->battery_voltage_sensor_error), BpBool(), "battery_voltage_sensor_error");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->battery_current_sensor_error), BpBool(), "battery_current_sensor_error");
    fds[7] = BpMessageFieldDescriptor((void *)&(m->battery_current_sensor_adjust_error), BpBool(), "battery_current_sensor_adjust_error");
    fds[8] = BpMessageFieldDescriptor((void *)&(m->motor_current_sensor_adjust_error), BpBool(), "motor_current_sensor_adjust_error");
    fds[9] = BpMessageFieldDescriptor((void *)&(m->accelerator_position_error), BpBool(), "accelerator_position_error");
    fds[10] = BpMessageFieldDescriptor((void *)&(m->padding1), BpUint(1, sizeof(uint8_t)), "padding1");
    fds[11] = BpMessageFieldDescriptor((void *)&(m->controller_voltage_sensor_error), BpBool(), "controller_voltage_sensor_error");
    fds[12] = BpMessageFieldDescriptor((void *)&(m->padding2), BpUint(2, sizeof(uint8_t)), "padding2");
    fds[13] = BpMessageFieldDescriptor((void *)&(m->power_system_error), BpBool(), "power_system_error");
    fds[14] = BpMessageFieldDescriptor((void *)&(m->overcurrent_error), BpBool(), "overcurrent_error");
    fds[15] = BpMessageFieldDescriptor((void *)&(m->padding3), BpUint(1, sizeof(uint8_t)), "padding3");
    fds[16] = BpMessageFieldDescriptor((void *)&(m->overvoltage_error), BpBool(), "overvoltage_error");
    fds[17] = BpMessageFieldDescriptor((void *)&(m->padding4), BpUint(1, sizeof(uint8_t)), "padding4");
    fds[18] = BpMessageFieldDescriptor((void *)&(m->overcurrent_limit), BpBool(), "overcurrent_limit");
    fds[19] = BpMessageFieldDescriptor((void *)&(m->padding5), BpUint(2, sizeof(uint8_t)), "padding5");
    fds[20] = BpMessageFieldDescriptor((void *)&(m->motor_system_error), BpBool(), "motor_system_error");
    fds[21] = BpMessageFieldDescriptor((void *)&(m->motor_lock), BpBool(), "motor_lock");
    fds[22] = BpMessageFieldDescriptor((void *)&(m->hall_sensor_short), BpBool(), "hall_sensor_short");
    fds[23] = BpMessageFieldDescriptor((void *)&(m->hall_sensor_open), BpBool(), "hall_sensor_open");
    fds[24] = BpMessageFieldDescriptor((void *)&(m->padding6), BpUint(4, sizeof(uint8_t)), "padding6");
    fds[25] = BpMessageFieldDescriptor((void *)&(m->overheat_level), BpUint(2, sizeof(uint8_t)), "overheat_level");
}

void BpXXXProcessBitprotoMotorControllerError(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoMotorControllerError *m = (struct BitprotoMotorControllerError *)(data);
    struct BpMessageFieldDescriptor field_descriptors[26];
    BpFieldDescriptorsInitBitprotoMotorControllerError(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 26, 32, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoMotorControllerError(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoMotorControllerError *m = (struct BitprotoMotorControllerError *)(data);
    struct BpMessageFieldDescriptor field_descriptors[26];
    BpFieldDescriptorsInitBitprotoMotorControllerError(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 26, 32, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoMotorControllerError(struct BitprotoMotorControllerError *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoMotorControllerError((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoMotorControllerError(struct BitprotoMotorControllerError *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoMotorControllerError((void *)m, &ctx);
    return 0;
}

int JsonBitprotoMotorControllerError(struct BitprotoMotorControllerError *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoMotorControllerError((void *)m, &ctx);
    return ctx.n;
}