// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__POWER_AUX_H__
#define __BITPROTO__POWER_AUX_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Number of bytes to encode struct BitprotoPowerAuxErrorStruct
#define BYTES_LENGTH_BITPROTO_POWER_AUX_ERROR_STRUCT 1

struct BitprotoPowerAuxErrorStruct {
    bool fan_error; // 1bit
    bool brake_light_error; // 1bit
    bool headlight_error; // 1bit
    bool bms_strobe_error; // 1bit
    bool left_turn_error; // 1bit
    bool right_turn_error; // 1bit
};

// Encode struct BitprotoPowerAuxErrorStruct to given buffer s.
int EncodeBitprotoPowerAuxErrorStruct(struct BitprotoPowerAuxErrorStruct *m, unsigned char *s);
// Decode struct BitprotoPowerAuxErrorStruct from given buffer s.
int DecodeBitprotoPowerAuxErrorStruct(struct BitprotoPowerAuxErrorStruct *m, unsigned char *s);
// Format struct BitprotoPowerAuxErrorStruct to a json format string.
int JsonBitprotoPowerAuxErrorStruct(struct BitprotoPowerAuxErrorStruct *m, char *s);

void BpXXXProcessBitprotoPowerAuxErrorStruct(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBitprotoPowerAuxErrorStruct(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif