// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__POWER_AUX_H__
#define __BITPROTO__POWER_AUX_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Number of bytes to encode struct BitprotoPowerAuxError
#define BYTES_LENGTH_BITPROTO_POWER_AUX_ERROR 1

struct BitprotoPowerAuxError {
    bool fan_error; // 1bit
    bool brake_light_error; // 1bit
    bool headlight_error; // 1bit
    bool bms_strobe_error; // 1bit
    bool left_turn_error; // 1bit
    bool right_turn_error; // 1bit
};

// Encode struct BitprotoPowerAuxError to given buffer s.
int EncodeBitprotoPowerAuxError(struct BitprotoPowerAuxError *m, unsigned char *s);
// Decode struct BitprotoPowerAuxError from given buffer s.
int DecodeBitprotoPowerAuxError(struct BitprotoPowerAuxError *m, unsigned char *s);
// Format struct BitprotoPowerAuxError to a json format string.
int JsonBitprotoPowerAuxError(struct BitprotoPowerAuxError *m, char *s);

void BpXXXProcessBitprotoPowerAuxError(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBitprotoPowerAuxError(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif