// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "solar_bp.h"

void BpFieldDescriptorsInitBitprotoSolarCurrent(struct BitprotoSolarCurrent *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->total_current), BpUint(16, sizeof(uint16_t)), "total_current");
}

void BpXXXProcessBitprotoSolarCurrent(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoSolarCurrent *m = (struct BitprotoSolarCurrent *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitBitprotoSolarCurrent(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 16, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoSolarCurrent(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoSolarCurrent *m = (struct BitprotoSolarCurrent *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitBitprotoSolarCurrent(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 16, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoSolarCurrent(struct BitprotoSolarCurrent *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoSolarCurrent((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoSolarCurrent(struct BitprotoSolarCurrent *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoSolarCurrent((void *)m, &ctx);
    return 0;
}

int JsonBitprotoSolarCurrent(struct BitprotoSolarCurrent *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoSolarCurrent((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBitprotoSolarVoltage(struct BitprotoSolarVoltage *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->panel1_voltage), BpUint(16, sizeof(uint16_t)), "panel1_voltage");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->panel2_voltage), BpUint(16, sizeof(uint16_t)), "panel2_voltage");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->panel3_voltage), BpUint(16, sizeof(uint16_t)), "panel3_voltage");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->panel4_voltage), BpUint(16, sizeof(uint16_t)), "panel4_voltage");
}

void BpXXXProcessBitprotoSolarVoltage(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoSolarVoltage *m = (struct BitprotoSolarVoltage *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitBitprotoSolarVoltage(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 64, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoSolarVoltage(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoSolarVoltage *m = (struct BitprotoSolarVoltage *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitBitprotoSolarVoltage(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 64, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoSolarVoltage(struct BitprotoSolarVoltage *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoSolarVoltage((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoSolarVoltage(struct BitprotoSolarVoltage *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoSolarVoltage((void *)m, &ctx);
    return 0;
}

int JsonBitprotoSolarVoltage(struct BitprotoSolarVoltage *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoSolarVoltage((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBitprotoSolarTemp(struct BitprotoSolarTemp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->panel1_temp), BpUint(16, sizeof(uint16_t)), "panel1_temp");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->panel2_temp), BpUint(16, sizeof(uint16_t)), "panel2_temp");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->panel3_temp), BpUint(16, sizeof(uint16_t)), "panel3_temp");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->panel4_temp), BpUint(16, sizeof(uint16_t)), "panel4_temp");
}

void BpXXXProcessBitprotoSolarTemp(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoSolarTemp *m = (struct BitprotoSolarTemp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitBitprotoSolarTemp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 64, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoSolarTemp(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoSolarTemp *m = (struct BitprotoSolarTemp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitBitprotoSolarTemp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 64, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoSolarTemp(struct BitprotoSolarTemp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoSolarTemp((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoSolarTemp(struct BitprotoSolarTemp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoSolarTemp((void *)m, &ctx);
    return 0;
}

int JsonBitprotoSolarTemp(struct BitprotoSolarTemp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoSolarTemp((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBitprotoSolarPhoto(struct BitprotoSolarPhoto *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->panel1_photo), BpUint(16, sizeof(uint16_t)), "panel1_photo");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->panel2_photo), BpUint(16, sizeof(uint16_t)), "panel2_photo");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->panel3_photo), BpUint(16, sizeof(uint16_t)), "panel3_photo");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->panel4_photo), BpUint(16, sizeof(uint16_t)), "panel4_photo");
}

void BpXXXProcessBitprotoSolarPhoto(void *data, struct BpProcessorContext *ctx) {
    struct BitprotoSolarPhoto *m = (struct BitprotoSolarPhoto *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitBitprotoSolarPhoto(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 64, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBitprotoSolarPhoto(void *data, struct BpJsonFormatContext *ctx) {
    struct BitprotoSolarPhoto *m = (struct BitprotoSolarPhoto *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitBitprotoSolarPhoto(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 64, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBitprotoSolarPhoto(struct BitprotoSolarPhoto *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBitprotoSolarPhoto((void *)m, &ctx);
    return 0;
}

int DecodeBitprotoSolarPhoto(struct BitprotoSolarPhoto *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBitprotoSolarPhoto((void *)m, &ctx);
    return 0;
}

int JsonBitprotoSolarPhoto(struct BitprotoSolarPhoto *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBitprotoSolarPhoto((void *)m, &ctx);
    return ctx.n;
}