// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__SOLAR_H__
#define __BITPROTO__SOLAR_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Number of bytes to encode struct BitprotoSolarCurrent
#define BYTES_LENGTH_BITPROTO_SOLAR_CURRENT 2

struct BitprotoSolarCurrent {
    uint16_t total_current; // 16bit
};

// Number of bytes to encode struct BitprotoSolarVoltage
#define BYTES_LENGTH_BITPROTO_SOLAR_VOLTAGE 8

struct BitprotoSolarVoltage {
    uint16_t panel1_voltage; // 16bit
    uint16_t panel2_voltage; // 16bit
    uint16_t panel3_voltage; // 16bit
    uint16_t panel4_voltage; // 16bit
};

// Number of bytes to encode struct BitprotoSolarTemp
#define BYTES_LENGTH_BITPROTO_SOLAR_TEMP 8

struct BitprotoSolarTemp {
    uint16_t panel1_temp; // 16bit
    uint16_t panel2_temp; // 16bit
    uint16_t panel3_temp; // 16bit
    uint16_t panel4_temp; // 16bit
};

// Number of bytes to encode struct BitprotoSolarPhoto
#define BYTES_LENGTH_BITPROTO_SOLAR_PHOTO 8

struct BitprotoSolarPhoto {
    uint16_t panel1_photo; // 16bit
    uint16_t panel2_photo; // 16bit
    uint16_t panel3_photo; // 16bit
    uint16_t panel4_photo; // 16bit
};

// Encode struct BitprotoSolarCurrent to given buffer s.
int EncodeBitprotoSolarCurrent(struct BitprotoSolarCurrent *m, unsigned char *s);
// Decode struct BitprotoSolarCurrent from given buffer s.
int DecodeBitprotoSolarCurrent(struct BitprotoSolarCurrent *m, unsigned char *s);
// Format struct BitprotoSolarCurrent to a json format string.
int JsonBitprotoSolarCurrent(struct BitprotoSolarCurrent *m, char *s);

// Encode struct BitprotoSolarVoltage to given buffer s.
int EncodeBitprotoSolarVoltage(struct BitprotoSolarVoltage *m, unsigned char *s);
// Decode struct BitprotoSolarVoltage from given buffer s.
int DecodeBitprotoSolarVoltage(struct BitprotoSolarVoltage *m, unsigned char *s);
// Format struct BitprotoSolarVoltage to a json format string.
int JsonBitprotoSolarVoltage(struct BitprotoSolarVoltage *m, char *s);

// Encode struct BitprotoSolarTemp to given buffer s.
int EncodeBitprotoSolarTemp(struct BitprotoSolarTemp *m, unsigned char *s);
// Decode struct BitprotoSolarTemp from given buffer s.
int DecodeBitprotoSolarTemp(struct BitprotoSolarTemp *m, unsigned char *s);
// Format struct BitprotoSolarTemp to a json format string.
int JsonBitprotoSolarTemp(struct BitprotoSolarTemp *m, char *s);

// Encode struct BitprotoSolarPhoto to given buffer s.
int EncodeBitprotoSolarPhoto(struct BitprotoSolarPhoto *m, unsigned char *s);
// Decode struct BitprotoSolarPhoto from given buffer s.
int DecodeBitprotoSolarPhoto(struct BitprotoSolarPhoto *m, unsigned char *s);
// Format struct BitprotoSolarPhoto to a json format string.
int JsonBitprotoSolarPhoto(struct BitprotoSolarPhoto *m, char *s);

void BpXXXProcessBitprotoSolarCurrent(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBitprotoSolarCurrent(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessBitprotoSolarVoltage(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBitprotoSolarVoltage(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessBitprotoSolarTemp(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBitprotoSolarTemp(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessBitprotoSolarPhoto(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBitprotoSolarPhoto(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif